### ISSUE TITLE
"See all responses to this analytic" button leads to 404

### ISSUE THREAD

**Issue by ibara** [PECE-project/pece-distro#101]
Hi Renato --

See here: https://csrg.cc/?q=annotions/question/11/artifact/2
When you click the "See all responses to this analytic" button, you get a hard 404.

**Comment by revagomes** [comment]
Brian, 

I checked that the link points to node id #9. When trying to access the same page using an alternative URL (https://csrg.cc/?q=node/9) it is working fine. It looks an issue on 'Clean URL' setup for this installation. It might be an issue on the webserver settings or an issue on URL alias on your site configuration settings.  

Let me know if you want me to review this settings. I'll have to access the master admin account.

**Comment by ibara** [comment]
I forgot to switch AllowOverride All on.
We're good, thanks for the cluebat!
