### ISSUE TITLE
Error message in media browser

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#106]
Getting this media browser error message in both Chrome and Safari when I try to upload an image for a new photo essay.

![Screen Shot 2020-09-10 at 11 30 35 AM](https://user-images.githubusercontent.com/6000846/92783900-06360b00-f35b-11ea-8f76-1b609f3673bd.png)

**Comment by revagomes** [comment]
I noticed issues on file upload when using private file system.
I will have a better look on it and I let you know if any news.

**Comment by revagomes** [comment]
Here is a demo video of a workaround showing how to fix upload images when its thumbnail gets broken/don't open after file upload:

https://www.loom.com/share/fc2dc159b58c4927b5b01537bcf1f818

**Comment by Honoluluskye** [comment]
Thanks but I can't even get to the upload meta-data page. I get the error after I click the upload button or "next". Today this is the error I got when I clicked the upload button
![Screen Shot 2020-10-14 at 11 23 35 AM](https://user-images.githubusercontent.com/6000846/96029652-ce196080-0e0f-11eb-8d22-333f964c9003.png)
