### ISSUE TITLE
Content display issue

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#11]
Navigating to the group "STS@RPI" on stsinfrastructures.org brings me to a display where one of the group's photo essay is displayed as a thumbnail image and "View Essay" link in the upper left of the screen, with no other content. 
I believe this is the error message: Failed to load resource: the server responded with a status of 500 (Service unavailable (with message))
I also have screenshots if helpful.

**Comment by lindsaypoirier** [comment]
For record, this was due to image artifacts getting deleted after it had been included in a photo essay.

**Comment by revagomes** [comment]
Fixed on #41
