### ISSUE TITLE
Full Name Error

### ISSUE THREAD

**Issue by Jradams1-uci** [PECE-project/pece-distro#111]
Whenever I log into Disaster STS as an administrator, I receive an error notice stating that "Briana Leone hasn't a full name. Please Contact Briana Leone to insert a valid full name." I contacted Briana about it and she informed me that she has been receiving the error notification as well. 
<img width="1091" alt="Screen Shot 2020-10-17 at 1 36 55 PM" src="https://user-images.githubusercontent.com/68704157/96350971-2f466b80-107e-11eb-93e3-a4b4fa435dd5.png">

**Comment by revagomes** [comment]
Fixed on PECE v1.29.1
