### ISSUE TITLE
Unable to add thumbnail

### ISSUE THREAD

**Issue by Morgansarao** [PECE-project/pece-distro#112]
I am unable to add a thumbnail image to any PECE essays. When I try and add a thumbnail, and get an error saying that it was unable to be "loaded for cropping".

**Comment by revagomes** [comment]
@Morgansarao, 

Are you still having any issue to add thumbnail images to PECE Essays?
 
I've tried uploading a new thumbnail image to a PECE Essay I have on Center for Ethnography and it worked fine. 

If you're still having issues, I'll ask you for more information like the website URL, the user role of the account you have (researcher, contributor, administrator) and a brief description on your workflow so I'll have better idea on how to reproduce that error with the same setup you have.

**Comment by akenner** [comment]
We're no longer have an issue with this @revagomes. Thanks for checking in on it!
