### ISSUE TITLE
Insert valid full name error

### ISSUE THREAD

**Issue by Morgansarao** [PECE-project/pece-distro#113]
![Screenshot 2020-10-09 at 11 58 56 AM](https://user-images.githubusercontent.com/72888666/97199926-f6e21400-1786-11eb-812e-7930e9ebb9ca.png) 
When I upload an artifact, or create a PECE essay on HousingEnergy, I receive an error saying that the users who are contributors to the artifact/essay don't have a full name, and that a valid full name needs to be added.

**Comment by revagomes** [comment]
Fixed on PECE v1.29.1
