### ISSUE TITLE
Issue Uploading PDFs and Images

### ISSUE THREAD

**Issue by grh249** [PECE-project/pece-distro#117]
Whenever I try to upload a PDF or image to the Disaster-STS-Network I received an error message. I have tried to do it using Safari and Chrome and it did not work either time.
<img width="575" alt="Screen Shot 2020-11-20 at 9 34 31 AM" src="https://user-images.githubusercontent.com/74788648/99831484-ffbecf00-2b13-11eb-95c0-0d86b4d075df.png">

**Comment by revagomes** [comment]
@grh249,
Are you still having issues uploading PDF/Image files?

I've just created a new PDF artifact and another Image artifact on DSTS and both uploads worked well. 
Please have another try.

 I'll close this issue. Feel free to reopen it issue if necessary.
