### ISSUE TITLE
Creating Images is down

### ISSUE THREAD

**Issue by BrianaLeone** [PECE-project/pece-distro#118]
I tried creating an image artifact but it repeatedly gives me an 'error' message. I tried both uploading on the private and public server but I get the same results. I don't get the same issue when I'm embedding the images inside PECE essays, simply when creating image artifacts.
![Screen Shot 2020-12-03 at 9 18 03 AM](https://user-images.githubusercontent.com/72934949/101043254-1b7e9800-354c-11eb-9776-e91bd9744ff3.png)

**Comment by akenner** [comment]
No one else on our team is having this issue so we are assuming that it is Briana's internet connection. I think we can close this issue, in other words.

**Comment by ibara** [comment]
Closing. But please re-open if others also have this issue.
