### ISSUE TITLE
Timeline Essay issue

### ISSUE THREAD

**Issue by BrianaLeone** [PECE-project/pece-distro#119]
I have tried to create a Timeline essay on Housing Energy but it will not allow me to add other PECE essays that are already on the platform within that essay. The essays I am typing in are open and should be visible to add to the essay, however the system does not find/recognize them.

**Comment by revagomes** [comment]
@BrianaLeone,
Timeline Essays accept only Artifacts (for now). 

As a workaround you might create an Artifact that works as a placeholder holding the link to the Essay:

1. Create a new Text artifact and add the link to the Essay on the artifact's description field.
2. Go to your Timeline Essay and add a new Timeline entry pointing to the text artifact you just created.
3. Fill all fields as usual, but on the description field you'll paste the Essay URL address. 

Users can go directly to it by clicking the link without having to access the text artifact first. 
In case of users get to the Text artifact for any reason they will also find the Essay's link on artifact's description. 

Here is an example of the process I described above:   
http://energyrights.info/content/timeline-essay-test/timeline
