### ISSUE TITLE
photo essay not showing items

### ISSUE THREAD

**Issue by emilyyork** [PECE-project/pece-distro#135]
I have added image artifacts to a photo essay, but when I view the photo essay it only shows the first one. I don't see any next previous buttons, or any way to advance it. Apologies if I'm just not remembering something. It's been a while.

**Comment by mikefortun** [comment]
posted this on slack but Angela reminded me you wont see it there:

emily, if it’s this one https://stsinfrastructures.org/content/nsf-sts-critical-pedagogy-workshop-bios# then I am seeing all of the photos, but it may be a different bug: the arrows to advance the slides are not showing up; if you click where you imagine the arrow SHOULD be, in the center of the right margin, you will see the slides advance.

**Comment by emilyyork** [comment]
Thanks so much! I will double check in the morning, but it sounds like just a UI thing with the arrows.

All the best,
Emily

Sent from my iPhone

On Jun 2, 2021, at 5:32 PM, mikefortun ***@***.***> wrote:

﻿ CAUTION: This email originated from outside of JMU. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

posted this on slack but Angela reminded me you wont see it there:

emily, if it’s this one https://stsinfrastructures.org/content/nsf-sts-critical-pedagogy-workshop-bios#<https://urldefense.proofpoint.com/v2/url?u=https-3A__stsinfrastructures.org_content_nsf-2Dsts-2Dcritical-2Dpedagogy-2Dworkshop-2Dbios-23&d=DwMFaQ&c=eLbWYnpnzycBCgmb7vCI4uqNEB9RSjOdn_5nBEmmeq0&r=JAMUZhBFD3VoLyvi581Tgw&m=kP3YCwEQh7iW3LNfU7z--uw9sU4_cChhAPKAWU6exj8&s=ORP3SYCF7n1qITaXdImyCp9CdxbcGmJl1_1M1UPVkmU&e=> then I am seeing all of the photos, but it may be a different bug: the arrows to advance the slides are not showing up; if you click where you imagine the arrow SHOULD be, in the center of the right margin, you will see the slides advance.

**Comment by revagomes** [comment]
A fix for that issue was released on PECE  v1.35. 

Closing.
