### ISSUE TITLE
Contributor can't "customize this page" on an essay

### ISSUE THREAD

**Issue by emilyyork** [PECE-project/pece-distro#136]
Hello, I have created an essay, but at least one of the contributors is not able to customize the page to add artifacts to it. I'm not sure if this is a bug or not? The essay is here: https://stsinfrastructures.org/content/sts-teaching-and-thinking-disabilities-workspace
The contributor is Courtney Forberg.

When she clicks "Customize this page" an error message pops up indicating she does not have access. Thank you!

**Comment by revagomes** [comment]
Hi @emilyyork,

Thanks for reporting that incident. I'll have a look on it and I'll let you know as soon as I have news.
