### ISSUE TITLE
Audio files don't bring error but not able to play

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#137]
I don't get any error on upload and it all looks successful but then when I try to play the audio file, nothing... 

see: https://www.researchdatashare.org/content/2021dec10-writing-meetingaudio-recording

and 

https://www.researchdatashare.org/content/2021june23-rds-design-teamaudio-recording

**Comment by revagomes** [comment]
@Honoluluskye 

What web browser and OS are you using?

Both links worked well when I tried playing the audio on Firefox (version 89.0.1) and Chromium (version 91.0.4472.101) on Linux - Elementary OS (version 5.1.7)

**Comment by lindsaypoirier** [comment]
Its working on Chrome!
