### ISSUE TITLE
user name not recognized

### ISSUE THREAD

**Issue by emilyyork** [PECE-project/pece-distro#138]
Hi All,
I have two participants in the STS as a Critical Pedagogy workshop who are having an issue in which they try to log in and get a username not recognized. It is not clear to me how they can definitively look it up to ensure they have the correct one, but I have run into this issue before so wanted to fill out a ticket. They are Malte Ziewitz and Sean M. Ferguson.

Thanks for your help!
Emily

**Comment by ibara** [comment]
Hello Emily --

Which PECE instance is this on? So that their user names can be looked up.

Thanks.

~Brian

**Comment by emilyyork** [comment]
STSInfrastructures.

Thanks!

From: Brian Callahan ***@***.***>
Reply-To: PECE-project/pece-distro ***@***.***>
Date: Wednesday, July 14, 2021 at 10:35 AM
To: PECE-project/pece-distro ***@***.***>
Cc: "York, Emily - yorker" ***@***.***>, Author ***@***.***>
Subject: Re: [PECE-project/pece-distro] user name not recognized (#138)

CAUTION: This email originated from outside of JMU. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

Hello Emily --

Which PECE instance is this on? So that their user names can be looked up.

Thanks.

~Brian

**Comment by revagomes** [comment]
Hi Emily, 

I did a password reset request for both user accounts so they will receive an e-mail with an one-time login link.

It's possible to do that by submitting the account's username via Password Reset form at  https://stsinfrastructures.org/user/password  
 
Please let me know if they were able to access their account that way.

Best,
