### ISSUE TITLE
Bug error message

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#14]
![screen shot 2018-08-28 at 9 37 28 pm](https://user-images.githubusercontent.com/6000846/44720623-b042f180-ab0a-11e8-9a24-79b1a44b9ad2.png)
Trying to click "annotate" on [this page](http://worldpece.org/content/liboiron-max-alex-zahara-and-ignace-schoot-2018-%E2%80%9Ccommunity-peer-review-method-bring-consent) and got the following error (see screenshot).

**Comment by lindsaypoirier** [comment]
Hi Angela, Have you noticed this on any other pages? Were you eventually able to annotate?

**Comment by Honoluluskye** [comment]
Stopped getting the error. Maybe connected with some lower Internet bandwidth in Sydney?
