### ISSUE TITLE
Adding text to the PECE documentation

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#144]
Please add the below text to the PECE documentation. Thank you!!

Zotero (https://www.zotero.org/) is an excellent and long-standing free and open-source scholarly tool; the PECE Design Group and many PECE users continue to use it as academics on a daily basis for reference management. When first designing PECE, we wanted to fully integrate Zotero into PECE, but at that time there was only a broken Drupal module connecting Zotero to Drupal’s Biblio module. We contracted to develop a fix that imports Zotero libraries and updates into PECE via the Biblio module. Even though we limited Zotero’s functionalities in several ways (most importantly, not to import PDFs stored in Zotero, creating artifacts that might be subject to copyright restrictions) the import feature has worked well enough. However, the Zotero integration with PECE has encountered several challenges as we have continued to use it within PECE, most notably the multiplication of copies of each reference, a bug we have been unable to locate and fix. Significant development work is required to more satisfactorily integrate Zotero with PECE, and so for the time being we are not providing support for the integration. We will be revisiting this issue after we successfully deploy the Drupal 9 update in Spring 2022. In the meantime, adopters of PECE may want to turn off the Zotero feed if it is on, or simply do not connect PECE to any Zotero libraries you might use in your research.

**Comment by revagomes** [comment]
@Honoluluskye 

Do you know which page should I place that notice?
[PECE Documentation](https://pece-project.github.io/drupal-pece/)

**Comment by Honoluluskye** [comment]
I think it can go in both user guide and site admin guide.
thanks.

*Angela Okune *(*she/her)*
angelaokune.me/
+1 (808) 358.8563 | @honoluluskye

**Comment by revagomes** [comment]
Done (https://github.com/PECE-project/drupal-pece/commit/19be4e09f9253ca0ac76b76e3406265dd8035d5e).
Closing.
