### ISSUE TITLE
Bug in STS Infra for full card view

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#156]
We would like full text view for this text artifact (https://stsinfrastructures.org/content/data-availability-statement-sorting-things-out-commentary-interview-geoffrey-bowker) in this essay (https://stsinfrastructures.org/content/sorting-things-out-commentary-interview-geoffrey-bowker/essay). 
![image](https://user-images.githubusercontent.com/6000846/168104475-d1989742-bf46-41d7-a0a9-df873926749b.png)

**Comment by revagomes** [comment]
@Honoluluskye,

I've updated the settings for the Essay you linked above. 

Please have a look on the Essay and let me know if it's now presented as expected.

This fix on "Card - full text" view mode will be added in the next release of PECE (v1.44).
