### ISSUE TITLE
Switch tabs on worldPECE about us page

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#16]
http://worldpece.org/about

@lindsaypoirier 
Not a big issue but instead of having the "Projects" tab be the first one on the World PECE about us page, I think the "About PECE" should come first so that is the first thing people see. Perhaps this link could also feature somewhere on the page since it is also very comprehensive and a good resource: https://pece.readthedocs.io/en/latest/intro.html

Thanks! (Trying to streamline info @so that I can point / hyperlink to somewhere when I talk about PECE).

**Comment by revagomes** [comment]
Done ;)

Here is a demo video on How to switch tabs order on About page:

https://www.loom.com/share/64b2945124b94c10b9010da18afa1c14
