### ISSUE TITLE
Registration on STSInfrastructures "unable to send email" but also "thank you for applying"

### ISSUE THREAD

**Issue by smurferguson** [PECE-project/pece-distro#166]
![pece stsinfra registration broke](https://user-images.githubusercontent.com/107972799/174933450-03eee204-d1e5-4310-8bcc-a7fd5975256b.jpg)

**Comment by revagomes** [comment]
@smurferguson The email notification settings of STSInfrastructures.org were reviewed and fixed. 

Please let me know if you're still experiencing that issue.
