### ISSUE TITLE
Registration on STSInfrastructures "unable to send email" but also "thank you for applying"

### ISSUE THREAD

**Issue by smurferguson** [PECE-project/pece-distro#167]
![pece stsinfra registration broke](https://user-images.githubusercontent.com/107972799/174933450-03eee204-d1e5-4310-8bcc-a7fd5975256b.jpg)

Trying to start a new group and everyone who has attempted since 6/18/2022 has received this error.

**Comment by revagomes** [comment]
Duplicates issue #166 
Closing it.
