### ISSUE TITLE
Difficulty installing PECE on Ubuntu 18.04 LTS server

### ISSUE THREAD

**Issue by ibara** [PECE-project/pece-distro#17]
Hey Renato --

We've been given a new server at UCI to install PECE onto. This one is different from what we've been using in the past--it's an Ubuntu 18.04 server, which comes with PHP 7.2

I've been having some issues getting PECE installed. Following the usual setup, I learned that php-mcrypt has been removed from PHP beginning with version 7.2, and when I go to /install.php I'm greeted with this error message:

```
Error
Error messageError: Call to undefined function xautoload() in include_once() (line 11 of /var/www/html/profiles/pece/modules/pece/pece_groups/pece_groups.module).
The website encountered an unexpected error. Please try again later.
```

Which is not one I've seen before. Any pointers you could give would be greatly appreciated.

Thanks!

~Brian

**Comment by revagomes** [comment]
Hi Brian,

This issue is caused by the fact that Drupal is not aware of XAutoload module initialization at that point on Drupal's installation phase.

I will prepare a hotfix to solve this issue and release a new version of the distro.

**Comment by ibara** [comment]
Thank you!
