### ISSUE TITLE
Redesign project page

### ISSUE THREAD

**Issue by revagomes** [PECE-project/pece-distro#49]

**Comment by lindsaypoirier** [comment]
Project pages should include a number of boxes for describing the project, including boxes for a Project image/banner) Contributors, Groups, Essays, Structured Analytics, Fieldsites, as well as the existing metadata for groups. When you're ready to start this one, let me know, and I will mock something up.

**Comment by revagomes** [comment]
[Projects page mockups](https://docs.google.com/presentation/d/1HUB56d7m1JBDiAJQfJMEgVqDXG1-Xgl-j6bCpLETiUk/edit#slide=id.g8c25dcea8e_0_0)

**Comment by revagomes** [comment]
This feature is added on [PECE v1.29.1](https://github.com/PECE-project/pece-distro/releases/tag/v1.29.1)

Closing.
