### ISSUE TITLE
PECE version 1.15 fails to install properly

### ISSUE THREAD

**Issue by ibara** [PECE-project/pece-distro#59]
Hey Renato and team --

Angela and I decided to go ahead and reinstall PECE from scratch on her server (researchdatashare.org).

However, PECE throws some errors after installation that I haven't seen before.

Screenshots below.

![2019-02-16-144046_1920x1080_scrot](https://user-images.githubusercontent.com/3883351/52904385-abc5de80-31f9-11e9-8bd2-11ac167d2e27.png)
![2019-02-16-144413_1920x1080_scrot](https://user-images.githubusercontent.com/3883351/52904386-ac5e7500-31f9-11e9-8bb0-5a40b39f5b3d.png)

**Comment by ibara** [comment]
Pinging @Honoluluskye so she can follow along.

**Comment by Honoluluskye** [comment]
Hi @revagomes any idea when this might possibly be fixed? Do you anticipate the new version will continue to be unstable for long? (if so, I might just go back to reinstalling the old version...) thanks!

**Comment by revagomes** [comment]
@Honoluluskye I've found what is causing the issue and I'm already working on a solution for it. It's hard to give an estimate. 
I suggest you to install the previous version (v1.14) and then upgrade when v1.15.1 is released. ;)

**Comment by ibara** [comment]
@revagomes Thanks! You're the best.
@Honoluluskye Want to connect some time this weekend? Or can I just go ahead whenever and set you up?
