### ISSUE TITLE
Can't access my dashboard

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#60]
Issue from: Aalok Khandekar at aalok.khandekar@gmail.com

Description: I have admin privileges for stsinfrastructures. Recently, in editing the STS Across Borders collection, I deleted an image artifact from the platform without first removing it from a photo essay: Since then, I can't seem to access this photo essay or the STS Across Borders PECE essay (http://stsinfrastructures.org/content/sts-across-borders-0/essay)  in which the photo essay above is embedded. Other PECE essays seem fine. Also, I can't seem to access my Dashboard any longer. It simply takes me to screen for which I am attaching a screenshot below.

Instance: STS Infrastructures

Error message: 

Screenshot: filename: error.jpg
id: vYn6VCvOzE5NnQKEQxdV2mGk-V6GZRES

**Comment by revagomes** [comment]
I've just removed the missing image artifact from *STS Across Borders PECE essay*. You are able to access this page again.

@lindsaypoirier Please let me know if dashboard is now working as expected.
