### ISSUE TITLE
The thumbnail image for the Urban Climate Adaptation group is broken on DSTS.

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#67]
Issue from: Alison Kenner at ali.kenner@gmail.com

Description: Basically, the thumbnail is still broken. Renato knows its an issue but I never submitted it here. The seminar is a week from now for Quotidian Anthropocene. Here is the page, https://disaster-sts-network.org/content/urban-climate-adaptation

Instance: Disaster STS Network

Error message: it's an error but i think you get it. 

Screenshot:

**Comment by revagomes** [comment]
I'm working on fixing this. 
As a workaround users can perform the following procedure to upload their files:

- Once you have already uploaded an image for the first time, on content create/edit form (Artifact, Group, Essay, etc)... click on  **"Edit"** Thumbnail (at the side of Thumbnail's Remove button) and an overlay edit form will be shown. 

- First, you must to select the checkbox to  **"Keep original filename"** and then upload the same file on **Replace file** field.

- Click save. Now the image will be saved correctly.As a workaround users can perform the following procedure to upload their files:

- Once you have already uploaded an image for the first time, On content create/edit form (Artifact, Group, Essay, etc)... click on  **"Edit"** Thumbnail (at the side of Thumbnail's Remove button) and an overlay edit form will be shown. 

- First, you must to select the checkbox to  **"Keep original filename"** and then upload the same file on **Replace file** field.

- Click save. Now the image will be saved correctly.

- After updating thumbnail image, Save content.

- After updating thumbnail image, Save content.

**Comment by revagomes** [comment]
It looks like a filesystem permission issue. I've set _file destination_ setting to 'group/thumbnail' on Group's thumbnail field settings so now DSTS is not having this issue anymore.
