### ISSUE TITLE
Corrupt URL or broken metadata field?

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#68]
Issue from: Alison Kenner at ali.kenner@gmail.com

Description: This issue is occurring in the Adaptation Plan PECE essay on DSTS (https://disaster-sts-network.org/content/adaptation-plans/essay). When we "Add an image" and connect it to the artifact URL (https://disaster-sts-network.org/content/plan-de-adaptaci%C3%B3n-al-cambio-clim%C3%A1tico-para-la-region-metropolitana-de-santiago-de-chile) the URL is too long for the Path field and ends up as a broken link. The field literally won't allow me to type in the rest of the URL. Any suggestions?

Instance: Disaster STS Network

Error message: 

Screenshot: filename: Screen_Shot_2019-07-22_at_9.53.26_AM.png
id: 5WJ59TDBpsjqn9urhi-oH_ZhJAYwekab

filename: Screen_Shot_2019-07-22_at_10.01.43_AM.png
id: OIaP-Swe6wEmeFw6Ux33neUr7Gt0lY6I

**Comment by revagomes** [comment]
I'll add "Create and edit URL aliases" permission to administrator user role. This way site administrators will be able to edit path alias for this content and set a shorter path that will fit field value size limit.

**Comment by revagomes** [comment]
Contents URL address is already updated (https://disaster-sts-network.org/content/plan-adaptacion-cambio-climatico-region-metropolitana-santiago-chile).
