### ISSUE TITLE
materials added in my PECE essay by a person who do not have a permission to do so

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#69]
Issue from: Duygu Kasdogan at duygukasdogan@gmail.com

Description: I have just gotten into the website to begin crafting our PECE essay: https://stsinfrastructures.org/content/innovating-sts-turkey-boundaries-translations-and-temporalities/essay

I come across artifacts that do not belong to our PECE essay, which are added by a person who do not have permission to edit the essay

Instance: STS Infrastructures

Error message: 

Screenshot:

**Comment by lindsaypoirier** [comment]
@revagomes A user saved their PECE Essay as default, which added all of the artifacts in their PECE Essay to any new essays and essays that hadn't yet been Saved as Custom. I reset the PECE Essay to the Default View, which fixed the other essays in the system. I'm not sure how these folks had access to Save as Default though. I checked, and they are not admin users in the system.

**Comment by revagomes** [comment]
"Save as default" feature is not available on  PECE Essays since version 1.24 of PECE.
