### ISSUE TITLE
Is there a way to re-order questions to display in a particular order in a PECE structured analytic? 

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#7]
What is the logic behind how questions in a structured analytic get displayed on the platform? It seems ad hoc -- I deliberately tried adding questions in the order I would like to see them displayed (and in the reverse order, too), but that didn't work. Wondering if I can get questions to display in a particular order of my choosing.

**Comment by lindsaypoirier** [comment]
Right now they are being ordered randomly - likely because they are technically tags, and we've set the other tags in the platform to order randomly. We can set them to order by created date.

**Comment by Honoluluskye** [comment]
Yes, this is an issue I have faced also. There also seems to be a bug with repeat analytics being displayed on different pages? http://worldpece.org/structured-analytics-questions-set/reading-qual-data-repository-platforms?page=1 The same questions are appearing (in random orders) on page 1, 2, 3. Not always the same but they are not static and it seems like some are missing?

**Comment by Honoluluskye** [comment]
Perhaps might be nice if they could be displayed either in alpha order or by time/date stamp when they were entered?

**Comment by revagomes** [comment]
<a href="https://www.loom.com/share/2aafce9525e049b2bb2e1dd17152b067"> <p>How to reorder Structured Analytics list? - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/public/2aafce9525e049b2bb2e1dd17152b067-with-play.gif"> </a>
