### ISSUE TITLE
drop down menu for group assignment for essays and artifacts disappeared

### ISSUE THREAD

**Issue by mikefortun** [PECE-project/pece-distro#78]
but only for the disaster-sts site
![image_2020_01_11T18_17_31_260Z](https://user-images.githubusercontent.com/5637089/72209159-49547d00-3460-11ea-9927-7cefa0fbf7d3.png)

**Comment by revagomes** [comment]
@mikefortun, 

Is the logged user (on the screenshot) a member of one or more groups?

**Comment by mikefortun** [comment]
yes, more than one
