### ISSUE TITLE
formatting in text artefact does not carry over to card view in PECE essay

### ISSUE THREAD

**Issue by mikefortun** [PECE-project/pece-distro#80]
so this
![image](https://user-images.githubusercontent.com/5637089/72223525-a6196b80-3524-11ea-915b-9525e5181426.png)
 appears as this

![image](https://user-images.githubusercontent.com/5637089/72223494-3d31f380-3524-11ea-92d2-32798d898839.png)

i realize there may not be a way to change this

**Comment by revagomes** [comment]
Fix available on PECE [v1.28.1](https://github.com/PECE-project/pece-distro/releases/tag/v1.28.1).
