### ISSUE TITLE
Cite As Box on Essays metadata pages and artifact pages

### ISSUE THREAD

**Issue by lindsaypoirier** [PECE-project/pece-distro#84]
A box should appear on artifact pages and on essay metadata pages indicating how to cite the material. Right now I'm thinking this could be a good format:

Artifacts:

[CREATOR(S)], "[TITLE]," [CREATED DATE], contributed by: [CONTRIBUTOR(s) (separated by comma)], last updated [LAST MODIFIED DATE], accessed [TODAY's DATE], _[PLATFORM NAME]_, _Platform for Experimental Collaborative Ethnography_, [ARK]. 

Essays:

[CREATOR(S)], "[TITLE]," _PLATFORM NAME_ , _Platform for Experimental Collaborative Ethnography_, , last updated [LAST MODIFIED DATE], accessed [TODAY's DATE], [ARK].  

Date format should be: 8 May 1924

If Created Date is blank, "n.d." should display in its place.

An '&' should be placed between two creators or contributors, and for three or more, commas should be placed between creators or contributors with the last separated by a ', & ':

Creator1 & Creator2
Creator1, Creator 2, & Creator3

**Comment by lindsaypoirier** [comment]
Examples: 

Artifact:

Sally Smith, "This is the title!," 21 January 1900, contributed by Nancy Whatshername, last modified 11 April 2020, accessed 20 April 2020, _Disaster STS Network, Platform for Experimental Collaborative Ethnography_, ark:00000000000. 

Essay:

Sally Smith, "This is the title!," _Disaster STS Network, Platform for Experimental Collaborative Ethnography_, last modified 10 April 2020, accessed 20 April 2020, ark:00000000000.

**Comment by lindsaypoirier** [comment]
On creating/editing artifacts and essay, there should be a new field called _Cite this content as part of the following project:_ that then lists the projects available on the platform. This would be a radio button and optional. The help description should be:
If this content is being created as part of a project on the platform, you may wish to indicate so in the content's recommended citation. If you leave this field blank, the platform will generate a general recommended citation. If you select a project in this field, the platform will customize the citation to include the project name. 

If a user left this field blank, the citation would appear as above. If they selected a project, the citation would be altered to the following:

Sally Smith, "This is the title!," Project Title, Disaster STS Network, Platform for Experimental Collaborative Ethnography, last modified 10 April 2020, accessed 20 April 2020, ark:00000000000.

**Comment by revagomes** [comment]
This features is available on [PECE v1.34](https://github.com/PECE-project/pece-distro/releases/tag/v1.34). 

Closing.
