### ISSUE TITLE
Image resize threshold of 10 remote images has been reached.

### ISSUE THREAD

**Issue by akenner** [PECE-project/pece-distro#92]
We simply have no idea what this means...
<img width="1221" alt="Screen Shot 2020-06-13 at 10 22 08 AM" src="https://user-images.githubusercontent.com/1063084/84571219-db3e1a00-ad5f-11ea-81a3-b8e76cb1488a.png">

And the user is having a problem with the PECE essay editor.

**Comment by revagomes** [comment]
@akenner  What is the version of PECE you are currently running? 

[PECE v1.24](https://github.com/PECE-project/pece-distro/releases/tag/v1.24) has an update that adjusts this issue.

**Comment by akenner** [comment]
OK, yes, we are running an older version. We need to update. I'll put it on my list :)
