### ISSUE TITLE
Unable to add to/save new artifacts in the timeline essay

### ISSUE THREAD

**Issue by akenner** [PECE-project/pece-distro#94]
Yesterday we created a timeline essay on the EVP instance. We were able to upload four artifacts, but now three separate users have received the following message when they have tried to add to it, including the original creator:

<img width="861" alt="Screen Shot 2020-07-08 at 3 12 15 PM" src="https://user-images.githubusercontent.com/1063084/86978690-78b51f80-c14d-11ea-8ad2-b550edf716ed.png">

<img width="1322" alt="Screen Shot 2020-07-08 at 3 09 46 PM" src="https://user-images.githubusercontent.com/1063084/86978706-7fdc2d80-c14d-11ea-9605-2027ebcb05e8.png">

**Comment by revagomes** [comment]
@akenner,  Is there any other field highlighted in red along with that error message?

**Comment by revagomes** [comment]
@akenner I've tried to reproduce this error by creating a new Timeline Essay and adding a few Artifacts on it but couldn't get that error message. Could you give me more details on what was the steps you guys did to get this message?

**Comment by akenner** [comment]
Hey @revagomes, we haven't used the timeline essay since then because it wasn't working. At our team meeting today I will assign someone to start working on a new one and we will test this out and see if its still a problem. Will try to get back to you tomorrow about this!
