### ISSUE TITLE
Add "Annotations" to Dashboard 

### ISSUE THREAD

**Issue by Honoluluskye** [PECE-project/pece-distro#95]
Have had multiple requests to modify Dashboard to display “annotations” as well as/ rather than “annotated artifacts". People interested in seeing all of their annotations that they have ever made...

**Comment by revagomes** [comment]
"Annotations" tab was added on users Dashboard on release [v1.29.1](https://github.com/PECE-project/pece-distro/releases/tag/v1.29.1)
